name: '${project.name}'
version: '${project.version}'
main: 'pl.mrstudios.deathrun.Main'
authors: [ 'SfenKer' ]
description: '${project.description}'
website: '${project.url}'
softdepend: ['PlaceholderAPI']

commands:
  deathrun:
    aliases:
      - 'dr'
  leave:
    aliases:
      - 'quit'
  start:
    aliases: []
